// このファイルは機械的に出力されました。

import type { NameDict } from "./types.js";

export const NAME_DICT: NameDict = [
  { source: "Mek", translation: "MEK" },
  { source: "R-Allosaurus", translation: "Rアロサウルス" },
  { source: "R-Equus", translation: "Rエクウス" },
  { source: "R-Gasbags", translation: "Rガスバッグ" },
  { source: "R-Carnotaurus", translation: "Rカルノタウルス" },
  { source: "R-Carbonemys", translation: "Rカルボネミス" },
  { source: "R-Giganotosaurus", translation: "Rギガノトサウルス" },
  { source: "R-Quetzal", translation: "Rケツァルコアトルス" },
  { source: "R-Dire Bear", translation: "Rショートフェイスベア" },
  { source: "R-Direwolf", translation: "Rダイアウルフ" },
  { source: "R-Daeodon", translation: "Rダエオドン" },
  { source: "R-Thylacoleo", translation: "Rティラコレオ" },
  { source: "R-Dilophosaur", translation: "Rディロフォサウルス" },
  { source: "R-Parasaur", translation: "Rパラサウロロフス" },
  { source: "R-Procoptodon", translation: "Rプロコプトドン" },
  { source: "R-Brontosaurus", translation: "Rブロントサウルス" },
  { source: "R-Velonasaur", translation: "Rベロナサウルス" },
  { source: "R-Megatherium", translation: "Rメガテリウム" },
  { source: "R-Reaper King", translation: "Rリーパーキング" },
  { source: "R-Reaper Queen", translation: "Rリーパークイーン" },
  { source: "R-Snow Owl", translation: "R雪フクロウ" },
  { source: "Tek Giganotosaurus", translation: "TEKギガノトサウルス" },
  { source: "Tek Quetzal", translation: "TEKケツァルコアトルス" },
  { source: "Tek Stegosaurus", translation: "TEKステゴサウルス" },
  { source: "Tek Stryder", translation: "TEKストライダー" },
  { source: "Tek Rex", translation: "TEKティラノサウルス" },
  { source: "Tek Triceratops", translation: "TEKトリケラトプス" },
  { source: "Tek Parasaur", translation: "TEKパラサウロロフス" },
  { source: "Tek Raptor", translation: "TEKユタラプトル" },
  { source: "VR Astrodelphis", translation: "VRアストロデルフィス" },
  { source: "VR Araneo", translation: "VRアラネオモーフス" },
  { source: "VR Argentavis", translation: "VRアルゲンタヴィス" },
  { source: "VR Allosaurus", translation: "VRアロサウルス" },
  { source: "VR Enforcer", translation: "VRエンフォーサー" },
  { source: "VR Onyc", translation: "VRオニコニクテリス" },
  { source: "VR Kaprosuchus", translation: "VRカプロスクス" },
  { source: "VR Mantis", translation: "VRカマキリ" },
  { source: "VR Chalicotherium", translation: "VRカリコテリウム" },
  { source: "VR Karkinos", translation: "VRカルキノス" },
  { source: "VR Carnotaurus", translation: "VRカルノタウルス" },
  { source: "VR Shadowmane", translation: "VRシャドウメイン" },
  { source: "VR Stegosaurus", translation: "VRステゴサウルス" },
  { source: "VR Tapejara", translation: "VRタペヤラ" },
  { source: "VR Titanoboa", translation: "VRティタノボア" },
  { source: "VR Dimorphodon", translation: "VRディモルフォドン" },
  { source: "VR Rex", translation: "VRティラノサウルス" },
  { source: "VR Dilophosaur", translation: "VRディロフォサウルス" },
  { source: "VR Terror Bird", translation: "VRテラーバード" },
  { source: "VR Triceratops", translation: "VRトリケラトプス" },
  { source: "VR Pachy", translation: "VRパキケファロサウルス" },
  { source: "VR Parasaur", translation: "VRパラサウロロフス" },
  { source: "VR Ferox", translation: "VRフェロクス" },
  { source: "VR Bloodstalker", translation: "VRブラッドストーカー" },
  { source: "VR Pulmonoscorpius", translation: "VRプルモノスコルピウス" },
  { source: "VR Velonasaur", translation: "VRベロナサウルス" },
  { source: "VR Megatherium", translation: "VRメガテリウム" },
  { source: "VR Megalania", translation: "VRメガラニア" },
  { source: "VR Raptor", translation: "VRユタラプトル" },
  { source: "VR Ravager", translation: "VRラベジャー" },
  { source: "VR Lymantria", translation: "VRリマントリア" },
  { source: "X-Argentavis", translation: "Xアルゲンタヴィス" },
  { source: "X-Allosaurus", translation: "Xアロサウルス" },
  { source: "X-Ankylosaurus", translation: "Xアンキロサウルス" },
  { source: "X-Ichthyosaurus", translation: "Xイクチオサウルス" },
  { source: "X-Otter", translation: "Xカワウソ" },
  { source: "X-Woolly Rhino", translation: "Xケブカサイ" },
  { source: "X-Sabertooth", translation: "Xサーベルタイガー" },
  { source: "X-Spino", translation: "Xスピノサウルス" },
  { source: "X-Sabertooth Salmon", translation: "Xセイバートゥース・サーモン" },
  { source: "X-Tapejara", translation: "Xタペヤラ" },
  { source: "X-Dunkleosteus", translation: "Xダンクルオステウス" },
  { source: "X-Rex", translation: "Xティラノサウルス" },
  { source: "X-Triceratops", translation: "Xトリケラトプス" },
  { source: "X-Basilosaurus", translation: "Xバシロサウルス" },
  { source: "X-Paraceratherium", translation: "Xパラケラテリウム" },
  { source: "X-Parasaur", translation: "Xパラサウロロフス" },
  { source: "X-Megalodon", translation: "Xメガロドン" },
  { source: "X-Mosasaurus", translation: "Xモササウルス" },
  { source: "X-Yutyrannus", translation: "Xユウティラヌス" },
  { source: "X-Raptor", translation: "Xユタラプトル" },
  { source: "X-Rock Elemental", translation: "Xロックエレメンタル" },
  { source: "Arthropluera", translation: "アースロプレウラ" },
  { source: "Aberrant Arthropluera", translation: "アースロプレウラ変種" },
  { source: "Ice Titan", translation: "アイス・タイタン" },
  { source: "Ice Golem", translation: "アイスエレメンタル" },
  { source: "Iceworm Male", translation: "アイスワーム(オス)" },
  { source: "Iceworm Queen", translation: "アイスワーム(女王)" },
  { source: "Ice Wyvern", translation: "アイスワイバーン" },
  { source: "Astrocetus", translation: "アストロセタス" },
  { source: "Astrodelphis", translation: "アストロデルフィス" },
  { source: "Attack Drone", translation: "アタックドローン" },
  { source: "Achatina", translation: "アフリカマイマイ" },
  { source: "Aberrant Achatina", translation: "アフリカマイマイ変種" },
  { source: "Amargasaurus", translation: "アマルガサウルス" },
  { source: "Araneo", translation: "アラネオモーフス" },
  { source: "Aberrant Araneo", translation: "アラネオモーフス変種" },
  { source: "Argentavis", translation: "アルゲンタヴィス" },
  { source: "Alpha X-Triceratops", translation: "アルファ・Xトリケラトプス" },
  { source: "Alpha Karkinos", translation: "アルファ・カルキノス" },
  { source: "Alpha Carnotaurus", translation: "アルファ・カルノタウルス" },
  { source: "Alpha King Titan", translation: "アルファ・コロッサル・タイタン" },
  {
    source: "Alpha Surface Reaper King",
    translation: "アルファ・サーフェス・リーパーキング",
  },
  { source: "Alpha Deathworm", translation: "アルファ・デスワーム" },
  { source: "Alpha Tusoteuthis", translation: "アルファ・トゥソテウティス" },
  { source: "Alpha Basilisk", translation: "アルファ・バジリスク" },
  { source: "Alpha Fire Wyvern", translation: "アルファ・ファイアワイバーン" },
  {
    source: "Alpha Blood Crystal Wyvern",
    translation: "アルファ・ブラッド・クリスタルワイバーン",
  },
  { source: "Alpha Megalodon", translation: "アルファ・メガロドン" },
  { source: "Alpha Mosasaur", translation: "アルファ・モササウルス" },
  { source: "Alpha Raptor", translation: "アルファ・ラプトル" },
  { source: "Alpha Leedsichthys", translation: "アルファ・リードシクティス" },
  { source: "Alpha T-Rex", translation: "アルファ・レックス" },
  { source: "Allosaurus", translation: "アロサウルス" },
  { source: "Ankylosaurus", translation: "アンキロサウルス" },
  { source: "Aberrant Ankylosaurus", translation: "アンキロサウルス変種" },
  { source: "Anglerfish", translation: "アンコウ" },
  { source: "Aberrant Anglerfish", translation: "アンコウ変種" },
  { source: "Andrewsarchus", translation: "アンドリューサルクス" },
  { source: "Ammonite", translation: "アンモナイト" },
  { source: "Yeti", translation: "イエティ" },
  { source: "Iguanodon", translation: "イグアノドン" },
  { source: "Aberrant Iguanodon", translation: "イグアノドン変種" },
  { source: "Ichthyosaurus", translation: "イクチオサウルス" },
  { source: "Ichthyornis", translation: "イクチオルニス" },
  { source: "Voidwyrm", translation: "ヴォイドワーム" },
  { source: "Eurypterid", translation: "ウミサソリ" },
  { source: "Equus", translation: "エクウス" },
  { source: "Aberrant Equus", translation: "エクウス変種" },
  { source: "Exo-Mek", translation: "エクソMEK" },
  {
    source: "Malfunctioned Mek Knight",
    translation: "エラーを起こしたMEKナイト",
  },
  {
    source: "Malfunctioned Tek Giganotosaurus",
    translation: "エラーを起こしたTEKギガノトサウルス",
  },
  {
    source: "Malfunctioned Tek Quetzal",
    translation: "エラーを起こしたTEKケツァルコアトルス",
  },
  {
    source: "Malfunctioned Tek Stegosaurus",
    translation: "エラーを起こしたTEKステゴサウルス",
  },
  {
    source: "Malfunctioned Tek Stryder",
    translation: "エラーを起こしたTEKストライダー",
  },
  {
    source: "Malfunctioned Tek Rex",
    translation: "エラーを起こしたTEKティラノサウルス",
  },
  {
    source: "Malfunctioned Tek Triceratops",
    translation: "エラーを起こしたTEKトリケラトプス",
  },
  {
    source: "Malfunctioned Tek Parasaur",
    translation: "エラーを起こしたTEKパラサウロロフス",
  },
  {
    source: "Malfunctioned Tek Raptor",
    translation: "エラーを起こしたTEKユタラプトル",
  },
  {
    source: "Malfunctioned Attack Drone",
    translation: "エラーを起こしたアタックドローン",
  },
  {
    source: "Malfunctioned Enforcer",
    translation: "エラーを起こしたエンフォーサー",
  },
  {
    source: "Brute Malfunctioned Tek Giganotosaurus",
    translation: "エラーを起こした凶暴なTEKギガノトサウルス",
  },
  {
    source: "Brute Malfunctioned Tek Rex",
    translation: "エラーを起こした凶暴なTEKティラノサウルス",
  },
  {
    source: "Malfunctioned Defense Unit",
    translation: "エラーを起こした防御ユニット",
  },
  {
    source: "Elemental Reaper King",
    translation: "エレメンタル・リーパーキング",
  },
  {
    source: "Ember Crystal Wyvern",
    translation: "エンバー・クリスタルワイバーン",
  },
  { source: "Enforcer", translation: "エンフォーサー" },
  { source: "Oviraptor", translation: "オヴィラプトル" },
  { source: "Onyc", translation: "オニコニクテリス" },
  { source: "Kairuku", translation: "カイルクペンギン" },
  { source: "Castoroides", translation: "カストロイデス" },
  { source: "Gasbags", translation: "ガスバッグ" },
  { source: "Gacha", translation: "ガチャ" },
  { source: "GachaClaus", translation: "ガチャクロース" },
  { source: "Kaprosuchus", translation: "カプロスクス" },
  { source: "Mantis", translation: "カマキリ" },
  { source: "Chalicotherium", translation: "カリコテリウム" },
  { source: "Gallimimus", translation: "ガリミムス" },
  { source: "Carcharodontosaurus", translation: "カルカロドントサウルス" },
  { source: "Karkinos", translation: "カルキノス" },
  { source: "Carnotaurus", translation: "カルノタウルス" },
  { source: "Aberrant Carnotaurus", translation: "カルノタウルス変種" },
  { source: "Carbonemys", translation: "カルボネミス" },
  { source: "Aberrant Carbonemys", translation: "カルボネミス変種" },
  { source: "Otter", translation: "カワウソ" },
  { source: "Aberrant Otter", translation: "カワウソ変種" },
  { source: "Gamma King Titan", translation: "ガンマ・コロッサル・タイタン" },
  { source: "Giganotosaurus", translation: "ギガノトサウルス" },
  { source: "Gigantopithecus", translation: "ギガントピテクス" },
  { source: "Aberrant Gigantopithecus", translation: "ギガントピテクス変種" },
  { source: "Cnidaria", translation: "クニダリア" },
  { source: "Aberrant Cnidaria", translation: "クニダリア変種" },
  { source: "Griffin", translation: "グリフィン" },
  { source: "Glowtail", translation: "グローテール" },
  { source: "Glowbug", translation: "グローバグ" },
  { source: "Quetzal", translation: "ケツァルコアトルス" },
  { source: "Woolly Rhino", translation: "ケブカサイ" },
  { source: "Kentrosaurus", translation: "ケントロサウルス" },
  { source: "Mantis Ghost", translation: "ゴーストカマキリ" },
  {
    source: "Surface Reaper King Ghost",
    translation: "ゴーストサーフェス・リーパーキング",
  },
  { source: "Direwolf Ghost", translation: "ゴーストダイアウルフ" },
  { source: "Rex Ghost", translation: "ゴーストティラノサウルス" },
  { source: "Basilisk Ghost", translation: "ゴーストバジリスク" },
  { source: "Bulbdog Ghost", translation: "ゴーストバルブドッグ" },
  { source: "Snow Owl Ghost", translation: "ゴースト雪フクロウ" },
  { source: "King Titan", translation: "コロッサル・タイタン" },
  { source: "Compy", translation: "コンプソグナトゥス" },
  { source: "Surface Reaper King", translation: "サーフェス・リーパーキング" },
  { source: "Sabertooth", translation: "サーベルタイガー" },
  { source: "Aberrant Salmon", translation: "サーモン変種" },
  {
    source: "Subterranean Reaper King",
    translation: "サブテラニアン・リーパーキング",
  },
  { source: "Summoner", translation: "サモナー" },
  { source: "Sarco", translation: "サルコスクス" },
  { source: "Aberrant Sarco", translation: "サルコスクス変種" },
  { source: "Seeker", translation: "シーカー" },
  { source: "Coelacanth", translation: "シーラカンス" },
  { source: "Aberrant Coelacanth", translation: "シーラカンス変種" },
  { source: "Sinomacrops", translation: "シノマクロプス" },
  { source: "Shinehorn", translation: "シャインホーン" },
  { source: "Oil Jug Bug", translation: "ジャグ・バグ(原油)" },
  { source: "Shadowmane", translation: "シャドウメイン" },
  { source: "Dire Bear", translation: "ショートフェイスベア" },
  { source: "Aberrant Dire Bear", translation: "ショートフェイスベア変種" },
  { source: "Super Turkey", translation: "スーパー七面鳥" },
  { source: "Scout", translation: "スカウト" },
  { source: "Skeletal Carnotaurus", translation: "スケルタル・カルノタウルス" },
  {
    source: "Skeletal Giganotosaurus",
    translation: "スケルタル・ギガノトサウルス",
  },
  { source: "Skeletal Quetzal", translation: "スケルタル・ケツァルコアトルス" },
  { source: "Skeletal Stego", translation: "スケルタル・ステゴサウルス" },
  { source: "Skeletal Rex", translation: "スケルタル・ティラノサウルス" },
  { source: "Skeletal Jerboa", translation: "スケルタル・トビネズミ" },
  { source: "Skeletal Trike", translation: "スケルタル・トリケラトプス" },
  { source: "Skeletal Bronto", translation: "スケルタル・ブロントサウルス" },
  { source: "Skeletal Raptor", translation: "スケルタル・ユタラプトル" },
  { source: "Sköll", translation: "スコル" },
  { source: "Steinbjörn", translation: "スタインヨルン" },
  { source: "Stegosaurus", translation: "ステゴサウルス" },
  { source: "Aberrant Stegosaurus", translation: "ステゴサウルス変種" },
  { source: "Spino", translation: "スピノサウルス" },
  { source: "Aberrant Spino", translation: "スピノサウルス変種" },
  { source: "Sabertooth Salmon", translation: "セイバートゥース・サーモン" },
  { source: "Zomdodo", translation: "ゾンビドードー" },
  { source: "Zombie Fire Wyvern", translation: "ゾンビファイアワイバーン" },
  { source: "Zombie Poison Wyvern", translation: "ゾンビポイズンワイバーン" },
  {
    source: "Zombie Lightning Wyvern",
    translation: "ゾンビライトニングワイバーン",
  },
  { source: "Direwolf", translation: "ダイアウルフ" },
  { source: "Dire Polar Bear", translation: "ダイアホッキョクグマ" },
  { source: "Daeodon", translation: "ダエオドン" },
  { source: "Tapejara", translation: "タペヤラ" },
  { source: "Dunkleosteus", translation: "ダンクルオステウス" },
  { source: "Chalk Golem", translation: "チョークエレメンタル" },
  { source: "Titanosaur", translation: "ティタノサウルス" },
  { source: "Titanoboa", translation: "ティタノボア" },
  { source: "Aberrant Titanoboa", translation: "ティタノボア変種" },
  { source: "Titanomyrma Soldier", translation: "ティタノミルマ・ソルジャー" },
  { source: "Titanomyrma Drone", translation: "ティタノミルマ・ドローン" },
  { source: "Deinonychus", translation: "デイノニクス" },
  { source: "Dinopithecus", translation: "ディノピテクス" },
  { source: "Dinopithecus King", translation: "ディノピテクスキング" },
  { source: "Diplocaulus", translation: "ディプロカウルス" },
  { source: "Aberrant Diplocaulus", translation: "ディプロカウルス変種" },
  { source: "Diplodocus", translation: "ディプロドクス" },
  { source: "Aberrant Diplodocus", translation: "ディプロドクス変種" },
  { source: "Dimetrodon", translation: "ディメトロドン" },
  { source: "Aberrant Dimetrodon", translation: "ディメトロドン変種" },
  { source: "Dimorphodon", translation: "ディモルフォドン" },
  { source: "Aberrant Dimorphodon", translation: "ディモルフォドン変種" },
  { source: "Thylacoleo", translation: "ティラコレオ" },
  { source: "Rex", translation: "ティラノサウルス" },
  { source: "Dilophosaur", translation: "ディロフォサウルス" },
  { source: "Desert Titan", translation: "デザート・タイタン" },
  { source: "Desert Titan Flock", translation: "デザート・タイタンの群れ" },
  { source: "Desmodus", translation: "デスモダス" },
  { source: "Deathworm", translation: "デスワーム" },
  { source: "Terror Bird", translation: "テラーバード" },
  { source: "Therizinosaur", translation: "テリジノサウルス" },
  { source: "Electrophorus", translation: "デンキウナギ" },
  { source: "Aberrant Electrophorus", translation: "デンキウナギ変種" },
  { source: "Tusoteuthis", translation: "トゥソテウティス" },
  { source: "Doedicurus", translation: "ドエディクルス" },
  { source: "Aberrant Doedicurus", translation: "ドエディクルス変種" },
  { source: "Dodo", translation: "ドードー" },
  { source: "DodoRex", translation: "ドードーレックス" },
  { source: "Dodo Wyvern", translation: "ドードーワイバーン" },
  { source: "Aberrant Dodo", translation: "ドードー変種" },
  { source: "Jerboa", translation: "トビネズミ" },
  { source: "Dragon", translation: "ドラゴン" },
  { source: "Triceratops", translation: "トリケラトプス" },
  { source: "Aberrant Triceratops", translation: "トリケラトプス変種" },
  { source: "Troodon", translation: "トロオドン" },
  {
    source: "Tropical Crystal Wyvern",
    translation: "トロピカル・クリスタルワイバーン",
  },
  { source: "Tropeognathus", translation: "トロペオグナトゥス" },
  { source: "Nameless", translation: "ネームレス" },
  { source: "Noglin", translation: "ノグリン" },
  { source: "Party Dodo", translation: "パーティードードー" },
  { source: "Pachy", translation: "パキケファロサウルス" },
  { source: "Pachyrhinosaurus", translation: "パキリノサウルス" },
  { source: "Vulture", translation: "ハゲワシ" },
  { source: "Basilisk", translation: "バジリスク" },
  { source: "Basilosaurus", translation: "バシロサウルス" },
  { source: "Hati", translation: "ハティ" },
  { source: "Bunny Oviraptor", translation: "バニーオヴィラプトル" },
  { source: "Bunny Dodo", translation: "バニードードー" },
  { source: "Parakeet Fish School", translation: "パラキートの魚群" },
  { source: "Paraceratherium", translation: "パラケラテリウム" },
  { source: "Aberrant Paraceratherium", translation: "パラケラテリウム変種" },
  { source: "Parasaur", translation: "パラサウロロフス" },
  { source: "Aberrant Parasaur", translation: "パラサウロロフス変種" },
  { source: "Baryonyx", translation: "バリオニクス" },
  { source: "Aberrant Baryonyx", translation: "バリオニクス変種" },
  { source: "Bulbdog", translation: "バルブドッグ" },
  { source: "Hyaenodon", translation: "ヒエノドン" },
  { source: "Ovis", translation: "ヒツジ" },
  { source: "Aberrant Ovis", translation: "ヒツジ変種" },
  { source: "Leech", translation: "ヒル" },
  { source: "Fire Wyvern", translation: "ファイアワイバーン" },
  {
    source: "Water Jug Bug",
    translation: "ファイル:ジャグバグ(水).png ジャグバグ(水)",
  },
  {
    source: "Bone Fire Wyvern",
    translation:
      "ファイル:スケルタル・ファイアワイバーン.png スケルタル・ファイアワイバーン",
  },
  { source: "Phiomia", translation: "フィオミア" },
  { source: "Fjordhawk", translation: "フィヨルドホーク" },
  { source: "Featherlight", translation: "フェザーライト" },
  { source: "Phoenix", translation: "フェニックス" },
  { source: "Ferox", translation: "フェロクス" },
  { source: "Fenrir", translation: "フェンリル" },
  { source: "Fenrisúlfr", translation: "フェンリル (ボス)" },
  { source: "Forest Titan", translation: "フォレスト・タイタン" },
  { source: "Forest Wyvern", translation: "フォレストワイバーン" },
  { source: "Pteranodon", translation: "プテラノドン" },
  {
    source: "Blood Crystal Wyvern",
    translation: "ブラッド・クリスタルワイバーン",
  },
  { source: "Bloodstalker", translation: "ブラッドストーカー" },
  { source: "Broodmother Lysrix", translation: "ブルードマザー" },
  { source: "Scorpion", translation: "プルモノスコルピウス" },
  {
    source: "Aberrant Pulmonoscorpius",
    translation: "プルモノスコルピウス変種",
  },
  { source: "Purlovia", translation: "プルロヴィア" },
  { source: "Polar Purlovia", translation: "プルロヴィア (雪原)" },
  { source: "Aberrant Purlovia", translation: "プルロヴィア変種" },
  { source: "Plesiosaur", translation: "プレシオサウルス" },
  { source: "Procoptodon", translation: "プロコプトドン" },
  { source: "Brontosaurus", translation: "ブロントサウルス" },
  { source: "Dung Beetle", translation: "フンコロガシ" },
  { source: "Aberrant Dung Beetle", translation: "フンコロガシ変種" },
  { source: "Beyla", translation: "ベイラ" },
  { source: "Beyla Spawn", translation: "ベイラ・スポーン" },
  { source: "Beta King Titan", translation: "ベータ・コロッサル・タイタン" },
  { source: "Beelzebufo", translation: "ベールゼブフォ" },
  { source: "Aberrant Beelzebufo", translation: "ベールゼブフォ変種" },
  { source: "Pegomastax", translation: "ペゴマスタクス" },
  { source: "Hesperornis", translation: "ヘスペロルニス" },
  { source: "Pelagornis", translation: "ペラゴルニス" },
  { source: "Velonasaur", translation: "ベロナサウルス" },
  { source: "Poison Wyvern", translation: "ポイズンワイバーン" },
  { source: "Polar Bear", translation: "ホッキョクグマ" },
  { source: "Magmasaur", translation: "マグマサウルス" },
  { source: "Macro-Summoner", translation: "マクロ・サモナー" },
  { source: "Macrophage", translation: "マクロファージ" },
  { source: "Managarmr", translation: "マナガルム" },
  { source: "Manta", translation: "マンタ" },
  { source: "Aberrant Manta", translation: "マンタ変種" },
  { source: "Manticore", translation: "マンティコア" },
  { source: "Mammoth", translation: "マンモス" },
  { source: "Microraptor", translation: "ミクロラプトル" },
  { source: "Maewing", translation: "メイウィング" },
  { source: "Mega Mek", translation: "メガMEK" },
  { source: "Megachelon", translation: "メガケロン" },
  { source: "Megatherium", translation: "メガテリウム" },
  { source: "Meganeura", translation: "メガネウラ" },
  { source: "Aberrant Meganeura", translation: "メガネウラ変種" },
  { source: "Megapithecus", translation: "メガピテクス" },
  { source: "Piranha", translation: "メガピラニア" },
  { source: "Aberrant Piranha", translation: "メガピラニア変種" },
  { source: "Megalania", translation: "メガラニア" },
  { source: "Aberrant Megalania", translation: "メガラニア変種" },
  { source: "Megaloceros", translation: "メガロケロス" },
  { source: "Megalosaurus", translation: "メガロサウルス" },
  { source: "Aberrant Megalosaurus", translation: "メガロサウルス変種" },
  { source: "Megalodon", translation: "メガロドン" },
  { source: "Mesopithecus", translation: "メソピテクス" },
  { source: "Mosasaurus", translation: "モササウルス" },
  { source: "Moschops", translation: "モスコプス" },
  { source: "Aberrant Moschops", translation: "モスコプス変種" },
  { source: "Morellatops", translation: "モレラトプス" },
  { source: "Thorny Dragon", translation: "モロクトカゲ" },
  { source: "Lamprey", translation: "ヤツメウナギ" },
  { source: "Yutyrannus", translation: "ユウティラヌス" },
  { source: "Raptor", translation: "ユタラプトル" },
  { source: "Aberrant Raptor", translation: "ユタラプトル変種" },
  { source: "Unicorn", translation: "ユニコーン" },
  { source: "Lightning Wyvern", translation: "ライトニングワイバーン" },
  { source: "Lava Elemental", translation: "ラヴァエレメンタル" },
  { source: "Rubble Bear", translation: "ラブル・ベアー" },
  { source: "Rubble Golem", translation: "ラブルゴーレム" },
  { source: "Ravager", translation: "ラベジャー" },
  { source: "Leedsichthys", translation: "リードシクティス" },
  { source: "Reaper King", translation: "リーパーキング" },
  { source: "Reaper Queen", translation: "リーパークイーン" },
  { source: "Liopleurodon", translation: "リオプレウロドン" },
  { source: "Lystrosaurus", translation: "リストロサウルス" },
  { source: "Aberrant Lystrosaurus", translation: "リストロサウルス変種" },
  { source: "Lymantria", translation: "リマントリア" },
  { source: "Roll Rat", translation: "ロールラット" },
  { source: "Rockwell", translation: "ロックウェル" },
  { source: "Rockwell Node", translation: "ロックウェル・ノード" },
  { source: "Rockwell Prime", translation: "ロックウェル・プライム" },
  { source: "Rockwell Tentacle", translation: "ロックウェルの触手" },
  { source: "Rock Elemental", translation: "ロックエレメンタル" },
  { source: "Rock Drake", translation: "ロックドレイク" },
  {
    source: "Corrupted Arthropluera",
    translation: "汚染されたアースロプレウラ",
  },
  { source: "Corrupted Avatar", translation: "汚染されたアバター" },
  {
    source: "Corrupted Chalicotherium",
    translation: "汚染されたカリコテリウム",
  },
  { source: "Corrupted Carnotaurus", translation: "汚染されたカルノタウルス" },
  {
    source: "Corrupted Giganotosaurus",
    translation: "汚染されたギガノトサウルス",
  },
  { source: "Corrupted Survivor", translation: "汚染されたサバイバー" },
  { source: "Corrupted Stegosaurus", translation: "汚染されたステゴサウルス" },
  { source: "Corrupted Spino", translation: "汚染されたスピノサウルス" },
  {
    source: "Corrupted Dimorphodon",
    translation: "汚染されたディモルフォドン",
  },
  { source: "Corrupted Rex", translation: "汚染されたティラノサウルス" },
  {
    source: "Corrupted Dilophosaur",
    translation: "汚染されたディロフォサウルス",
  },
  { source: "Corrupted Deathworm", translation: "汚染されたデスワーム" },
  { source: "Corrupted Triceratops", translation: "汚染されたトリケラトプス" },
  {
    source: "Corrupted Paraceratherium",
    translation: "汚染されたパラケラテリウム",
  },
  { source: "Corrupted Pteranodon", translation: "汚染されたプテラノドン" },
  { source: "Corrupted Raptor", translation: "汚染されたユタラプトル" },
  { source: "Corrupted Reaper King", translation: "汚染されたリーパーキング" },
  { source: "Corrupted Rock Drake", translation: "汚染されたロックドレイク" },
  { source: "Corrupted Wyvern", translation: "汚染されたワイバーン" },
  { source: "Corrupted Master Controller", translation: "汚染された支配者" },
  { source: "Corrupt Tumor", translation: "汚染された腫瘍" },
  { source: "Overseer", translation: "監督者" },
  { source: "Giant Bee", translation: "巨大ハチ" },
  { source: "Giant Queen Bee", translation: "巨大女王バチ" },
  { source: "Brute X-Allosaurus", translation: "凶暴なXアロサウルス" },
  { source: "Brute X-Spino", translation: "凶暴なXスピノサウルス" },
  { source: "Brute X-Rex", translation: "凶暴なXティラノサウルス" },
  { source: "Brute X-Megalodon", translation: "凶暴なXメガロドン" },
  { source: "Brute X-Mosasaurus", translation: "凶暴なXモササウルス" },
  { source: "Brute X-Yutyrannus", translation: "凶暴なXユウティラヌス" },
  { source: "Brute X-Raptor", translation: "凶暴なXユタラプトル" },
  {
    source: "Brute X-Rock Elemental",
    translation: "凶暴なXロックエレメンタル",
  },
  { source: "Brute Astrocetus", translation: "凶暴なアストロセタス" },
  { source: "Brute Araneo", translation: "凶暴なアラネオモーフス" },
  { source: "Brute Sarco", translation: "凶暴なサルコスクス" },
  { source: "Brute Seeker", translation: "凶暴なシーカー" },
  { source: "Brute Tusoteuthis", translation: "凶暴なトゥソテウティス" },
  { source: "Brute Basilosaurus", translation: "凶暴なバシロサウルス" },
  { source: "Brute Fire Wyvern", translation: "凶暴なファイアワイバーン" },
  { source: "Brute Ferox", translation: "凶暴なフェロクス" },
  { source: "Brute Bloodstalker", translation: "凶暴なブラッドストーカー" },
  { source: "Brute Plesiosaur", translation: "凶暴なプレシオサウルス" },
  { source: "Brute Magmasaur", translation: "凶暴なマグマサウルス" },
  { source: "Brute Mammoth", translation: "凶暴なマンモス" },
  { source: "Brute Megaloceros", translation: "凶暴なメガロケロス" },
  { source: "Brute Leedsichthys", translation: "凶暴なリードシクティス" },
  { source: "Golden Striped Megalodon", translation: "金縞のメガロドン" },
  {
    source: "Golden Striped Brute Megalodon",
    translation: "金縞の凶暴なメガロドン",
  },
  { source: "Enraged Triceratops", translation: "激怒したトリケラトプス" },
  {
    source: "Enraged Corrupted Rex",
    translation: "激怒した汚染されたティラノサウルス",
  },
  { source: "Trilobite", translation: "三葉虫" },
  { source: "Aberrant Trilobite", translation: "三葉虫変種" },
  { source: "Archaeopteryx", translation: "始祖鳥" },
  { source: "Eel Minion", translation: "子ウナギ (ミニオン)" },
  {
    source: "Experimental Giganotosaurus",
    translation: "実験体ギガノトサウルス",
  },
  {
    source: "Moeder, Master of the Ocean",
    translation: "深海の女王・ムーダー",
  },
  { source: "Snow Owl", translation: "雪フクロウ" },
  { source: "Insect Swarm", translation: "虫の大群" },
  { source: "Diseased Leech", translation: "病気持ちのヒル" },
  { source: "Defense Unit", translation: "防御ユニット" },
] as const;
