// このファイルは機械的に出力されました。

import type { NameDict } from "./types.js";

export const NAME_DICT: NameDict = [
  { source: "Archelon", translation: "アーケロン" },
  { source: "Arthropluera", translation: "アースロプレウラ" },
  { source: "Ice Wyvern", translation: "アイスワイバーン" },
  { source: "Astrocetus", translation: "アストロセタス" },
  { source: "Achatina", translation: "アフリカマイマイ" },
  { source: "Araneo", translation: "アラネオモーフス" },
  { source: "Argentavis", translation: "アルゲンタヴィス" },
  { source: "Armadoggo", translation: "アルマドッゴ" },
  { source: "Allosaurus", translation: "アロサウルス" },
  { source: "Ankylosaurus", translation: "アンキロサウルス" },
  { source: "Giant Bee", translation: "イキオオミツバチ" },
  { source: "Iguanodon", translation: "イグアノドン" },
  { source: "Ichthyosaurus", translation: "イクチオサウルス" },
  { source: "Ichthyornis", translation: "イクチオルニス" },
  { source: "Drakeling (Winter)", translation: "ウィンター・ドレイクリング" },
  { source: "Equus", translation: "エクウス" },
  { source: "Elderclaw", translation: "エルダークロー" },
  { source: "Enforcer", translation: "エンフォーサー" },
  { source: "Oasisaur", translation: "オアシサウルス" },
  { source: "Oviraptor", translation: "オヴィラプトル" },
  { source: "Drakeling (Autumn)", translation: "オータム・ドレイクリング" },
  { source: "Aureliax", translation: "オーレリアックス" },
  { source: "Ossidon", translation: "オシドン" },
  { source: "Onyc", translation: "オニコニクテリス" },
  { source: "Kairuku", translation: "カイルクペンギン" },
  { source: "Castoroides", translation: "カストロイデス" },
  { source: "Gasbags", translation: "ガスバッグ" },
  { source: "Gacha", translation: "ガチャ" },
  { source: "Kaprosuchus", translation: "カプロスクス" },
  { source: "Mantis", translation: "カマキリ" },
  { source: "Chalicotherium", translation: "カリコテリウム" },
  { source: "Gallimimus", translation: "ガリミムス" },
  { source: "Carcharodontosaurus", translation: "カルカロドントサウルス" },
  { source: "Karkinos", translation: "カルキノス" },
  { source: "Carnotaurus", translation: "カルノタウルス" },
  { source: "Carbonemys", translation: "カルボネミス" },
  { source: "Otter", translation: "カワウソ" },
  { source: "Gigadesmodus", translation: "ギガデスモダス" },
  { source: "Giganotosaurus", translation: "ギガノトサウルス" },
  { source: "Gigantopithecus", translation: "ギガントピテクス" },
  { source: "Gigantoraptor", translation: "ギガントラプトル" },
  { source: "Cryolophosaurus", translation: "クライオロフォサウルス" },
  { source: "Grand Tortugar", translation: "グランド・トルトゥガー" },
  { source: "Griffin", translation: "グリフィン" },
  { source: "Gloon", translation: "グルーン" },
  { source: "Glowtail", translation: "グローテール" },
  { source: "Quetzal", translation: "ケツァルコアトルス" },
  { source: "Woolly Rhino", translation: "ケブカサイ" },
  { source: "Ceratosaurus", translation: "ケラトサウルス" },
  { source: "Kentrosaurus", translation: "ケントロサウルス" },
  { source: "Cosmo", translation: "コスモ" },
  { source: "Compy", translation: "コンプソグナトゥス" },
  { source: "Sabertooth", translation: "サーベルタイガー" },
  { source: "Drakeling (Summer)", translation: "サマー・ドレイクリング" },
  { source: "Sarco", translation: "サルコスクス" },
  { source: "Coelacanth", translation: "シーラカンス" },
  { source: "Xiphactinus", translation: "シファクティヌス" },
  { source: "Shinehorn", translation: "シャインホーン" },
  { source: "Shastasaurus", translation: "シャスタサウルス" },
  { source: "Dire Bear", translation: "ショートフェイスベア" },
  { source: "Scout", translation: "スカウト" },
  { source: "Stegosaurus", translation: "ステゴサウルス" },
  { source: "Spino", translation: "スピノサウルス" },
  { source: "Drakeling (Spring)", translation: "スプリング・ドレイクリング" },
  { source: "Sabertooth Salmon", translation: "セイバートゥース・サーモン" },
  { source: "Solwyn", translation: "ソルウィン" },
  { source: "Direwolf", translation: "ダイアウルフ" },
  { source: "Dire Polar Bear", translation: "ダイアホッキョクグマ" },
  { source: "Daeodon", translation: "ダエオドン" },
  { source: "Tapejara", translation: "タペヤラ" },
  { source: "Dunkleosteus", translation: "ダンクルオステウス" },
  { source: "Chalk Elemental", translation: "チョークエレメンタル" },
  { source: "Titanosaur", translation: "ティタノサウルス" },
  { source: "Titanoboa", translation: "ティタノボア" },
  { source: "Deinosuchus", translation: "デイノスクス" },
  { source: "Deinotherium", translation: "ディノテリウム" },
  { source: "Deinonychus", translation: "デイノニクス" },
  { source: "Diplocaulus", translation: "ディプロカウルス" },
  { source: "Diplodocus", translation: "ディプロドクス" },
  { source: "Dimetrodon", translation: "ディメトロドン" },
  { source: "Dimorphodon", translation: "ディモルフォドン" },
  { source: "Thylacoleo", translation: "ティラコレオ" },
  { source: "Rex", translation: "ティラノサウルス" },
  { source: "Dilophosaur", translation: "ディロフォサウルス" },
  { source: "Desmodus", translation: "デスモダス" },
  { source: "Terror Bird", translation: "テラーバード" },
  { source: "Therizinosaur", translation: "テリジノサウルス" },
  { source: "Electrophorus", translation: "デンキウナギ" },
  { source: "Tusoteuthis", translation: "トゥソテウティス" },
  { source: "Doedicurus", translation: "ドエディクルス" },
  { source: "Dodo", translation: "ドードー" },
  { source: "Jerboa", translation: "トビネズミ" },
  { source: "Triceratops", translation: "トリケラトプス" },
  { source: "Dreadnoughtus", translation: "ドレッドノータス" },
  { source: "Dreadmare", translation: "ドレッドメア" },
  { source: "Troodon", translation: "トロオドン" },
  { source: "Bison", translation: "バイソン" },
  { source: "Pyromane", translation: "パイロメイン" },
  { source: "Pachyrhinosaurus", translation: "パキリノサウルス" },
  { source: "Vulture", translation: "ハゲワシ" },
  { source: "Basilisk", translation: "バジリスク" },
  { source: "Basilosaurus", translation: "バシロサウルス" },
  { source: "Parasaur", translation: "パラサウロロフス" },
  { source: "Baryonyx", translation: "バリオニクス" },
  { source: "Bulbdog", translation: "バルブドッグ" },
  { source: "Hyaenodon", translation: "ヒエノドン" },
  { source: "Ovis", translation: "ヒツジ" },
  { source: "Leech", translation: "ヒル" },
  { source: "Fire Wyvern", translation: "ファイアワイバーン" },
  { source: "Fasolasuchus", translation: "ファソラスクス" },
  { source: "Phiomia", translation: "フィオミア" },
  { source: "Featherlight", translation: "フェザーライト" },
  { source: "Phoenix", translation: "フェニックス" },
  { source: "Ferox", translation: "フェロクス" },
  { source: "Pteranodon", translation: "プテラノドン" },
  { source: "Bloodstalker", translation: "ブラッドストーカー" },
  { source: "Pulmonoscorpius", translation: "プルモノスコルピウス" },
  { source: "Purlovia", translation: "プルロヴィア" },
  { source: "Plesiosaur", translation: "プレシオサウルス" },
  { source: "Procoptodon", translation: "プロコプトドン" },
  { source: "Dung Beetle", translation: "フンコロガシ" },
  { source: "Veilwyn", translation: "ベールウィン" },
  { source: "Beelzebufo", translation: "ベールゼブフォ" },
  { source: "Pegomastax", translation: "ペゴマスタクス" },
  { source: "Hesperornis", translation: "ヘスペロルニス" },
  { source: "Pelagornis", translation: "ペラゴルニス" },
  { source: "Helicoprion", translation: "ヘリコプリオン" },
  { source: "Velonasaur", translation: "ベロナサウルス" },
  { source: "Poison Wyvern", translation: "ポイズンワイバーン" },
  { source: "Magmasaur", translation: "マグマサウルス" },
  { source: "Managarmr", translation: "マナガルム" },
  { source: "Malwyn", translation: "マルウィン" },
  { source: "Manta", translation: "マンタ" },
  { source: "Mammoth", translation: "マンモス" },
  { source: "Microraptor", translation: "ミクロラプトル" },
  { source: "Maeguana", translation: "メイグアナ" },
  { source: "Megachelon", translation: "メガケロン" },
  { source: "Megatherium", translation: "メガテリウム" },
  { source: "Piranha", translation: "メガピラニア" },
  { source: "Megalania", translation: "メガラニア" },
  { source: "Megaraptor", translation: "メガラプトル" },
  { source: "Megaloceros", translation: "メガロケロス" },
  { source: "Megalosaurus", translation: "メガロサウルス" },
  { source: "Megalodon", translation: "メガロドン" },
  { source: "Mesopithecus", translation: "メソピテクス" },
  { source: "Mosasaurus", translation: "モササウルス" },
  { source: "Moschops", translation: "モスコプス" },
  { source: "Morellatops", translation: "モレラトプス" },
  { source: "Thorny Dragon", translation: "モロクトカゲ" },
  { source: "Lamprey", translation: "ヤツメウナギ" },
  { source: "Yutyrannus", translation: "ユウティラヌス" },
  { source: "Raptor", translation: "ユタラプトル" },
  { source: "Unicorn", translation: "ユニコーン" },
  { source: "Lightning Wyvern", translation: "ライトニングワイバーン" },
  { source: "Ravager", translation: "ラベジャー" },
  { source: "Reaper King", translation: "リーパーキング" },
  { source: "Liopleurodon", translation: "リオプレウロドン" },
  { source: "Lystrosaurus", translation: "リストロサウルス" },
  { source: "Rhyniognatha", translation: "リニオグナタ" },
  { source: "Lymantria", translation: "リマントリア" },
  { source: "Roll Rat", translation: "ロールラット" },
  { source: "Rock Elemental", translation: "ロックエレメンタル" },
  { source: "Rock Drake", translation: "ロックドレイク" },
  { source: "Trilobite", translation: "三葉虫" },
  { source: "Archaeopteryx", translation: "始祖鳥" },
  { source: "Snow Owl", translation: "雪フクロウ" },
  { source: "Cat", translation: "猫" },
] as const;
