/*
    このファイルは、検索に使用する名前一覧を生成するためのツールです。
    create-values で生成したSpecies と辞書から日本語名の紐づけを行います。
*/

import fs from "node:fs";
import type { NameDict } from "../src/asb/migration/name-dict/types.js";
import { AllModSpecies } from "../src/asb/migration/values/index.js";

function deleteDuplicate(list: NameDict) {
  const tmpList1 = Array.from(
    new Map(list.map((obj) => [obj.source, obj])).values(),
  );
  const tmpList2 = Array.from(
    new Map(tmpList1.map((obj) => [obj.translation, obj])).values(),
  );
  return tmpList2;
}

function getNames(dict: NameDict, lang: string) {
  const valuesNames = AllModSpecies.flatMap((s) => s.species)
    .map((species) => species.name)
    .filter((s) => s !== null && s !== undefined);
  const safeDict = dict.filter((d) => valuesNames.includes(d.source));
  return deleteDuplicate(safeDict).sort((a, b) =>
    a.translation.localeCompare(b.translation, lang),
  );
}

/**
 * この関数は、いきものの名前の一覧を出力します。
 * @param outputPath 出力ファイルのパス
 */
function createConstTs(dict: NameDict, lang: string) {
  // values.ts の内容を作成
  const content = `
// このファイルは機械的に出力されました。

  import type { NameDict } from "./types.js";

  export const NAME_DICT: NameDict = [\n  ${dict
    .map((d) => `{source:"${d.source}",translation:"${d.translation}"},`)
    .join("\n")
    .trim()}\n] as const;
    `;

  // ファイルを出力
  fs.writeFileSync(
    `./src/asb/migration/name-dict/${lang}.ts`,
    content,
    "utf-8",
  );
}

function main() {
  const dict = getNames(DICT_JA, "ja");
  createConstTs(dict, "ja");
}

const DICT_JA: NameDict = [
  { source: "MEK", translation: "MEK" },
  { source: "アイスエレメンタル", translation: "Rock Elemental" },
  { source: "アイスワイバーン", translation: "Wyvern" },
  { source: "アクロカントサウルス", translation: "Acrocanthosaurus" },
  { source: "アーケロン", translation: "Archelon" },
  { source: "アストロセタス", translation: "Astrocetus" },
  { source: "アースロプレウラ", translation: "Arthropluera" },
  { source: "アフリカマイマイ", translation: "Achatina" },
  { source: "アラネオモーフス", translation: "Araneo" },
  { source: "アルゲンタヴィス", translation: "Argentavis" },
  { source: "アルマドッゴ", translation: "Armadoggo" },
  { source: "(特定条件で攻撃的)", translation: "Extinction" },
  { source: "アロサウルス", translation: "Allosaurus" },
  { source: "アンキロサウルス", translation: "Ankylosaurus" },
  { source: "アンコウ", translation: "Angler" },
  { source: "イキオオミツバチ", translation: "Giant Bee" },
  { source: "(特定条件で攻撃的)", translation: "The Island" },
  { source: "イグアノドン", translation: "Iguanodon" },
  { source: "イクチオサウルス", translation: "Ichthyosaurus" },
  { source: "イクチオルニス", translation: "Ichthyornis" },
  { source: "イーリン", translation: "Yi-Ling" },
  { source: "ウィンター・ドレイクリング", translation: "Drakeling" },
  { source: "エクウス", translation: "" },
  { source: "ユニコーン", translation: "Equus" },
  { source: "エルダークロー", translation: "Elderclaw" },
  { source: "エンフォーサー", translation: "Enforcer" },
  { source: "(特定条件で攻撃的)", translation: "Extinction" },
  { source: "オアシサウルス", translation: "Oasisaur" },
  { source: "オヴィラプトル", translation: "Oviraptor" },
  { source: "オシドン", translation: "Ossidon" },
  { source: "オータム・ドレイクリング", translation: "Drakeling" },
  { source: "オニコニクテリス", translation: "Onyc" },
  { source: "オーレリアックス", translation: "Aureliax" },
  { source: "カイルクペンギン", translation: "Kairuku" },
  { source: "カストロイデス", translation: "Castoroides" },
  { source: "(特定条件で攻撃的)", translation: "The Island" },
  { source: "ガスバッグ", translation: "Gasbags" },
  { source: "ガチャ", translation: "Gacha" },
  { source: "カプロスクス", translation: "Kaprosuchus" },
  { source: "カマキリ", translation: "Mantis" },
  { source: "カリコテリウム", translation: "Chalicotherium" },
  { source: "ガリミムス", translation: "Gallimimus" },
  { source: "カルカロドントサウルス", translation: "Carcharodontosaurus" },
  { source: "カルキノス", translation: "Karkinos" },
  { source: "カルノタウルス", translation: "Carnotaurus" },
  { source: "カルボネミス", translation: "Carbonemys" },
  { source: "カワウソ", translation: "Otter" },
  { source: "ギガデスモダス", translation: "Gigadesmodus" },
  { source: "ギガノトサウルス", translation: "Giganotosaurus" },
  { source: "ギガントピテクス", translation: "Gigantopithecus" },
  { source: "ギガントラプトル", translation: "Gigantoraptor" },
  { source: "クライオロフォサウルス", translation: "Cryolophosaurus" },
  { source: "グランド・トルトゥガー", translation: "Grand Tortugar" },
  { source: "グリフィン", translation: "Griffin" },
  { source: "グルーン", translation: "Gloon" },
  { source: "グローテール", translation: "Glowtail" },
  { source: "ケツァルコアトルス", translation: "Quetzal" },
  { source: "ケブカサイ", translation: "Woolly Rhino" },
  { source: "ケラトサウルス", translation: "Ceratosaurus" },
  { source: "ケントロサウルス", translation: "Kentrosaurus" },
  { source: "コスモ", translation: "Cosmo" },
  { source: "コンプソグナトゥス", translation: "Compy" },
  { source: "(特定条件で攻撃的)", translation: "The Island" },
  { source: "サーベルタイガー", translation: "Sabertooth" },
  { source: "サマー・ドレイクリング", translation: "Drakeling" },
  { source: "サルコスクス", translation: "Sarco" },
  { source: "三葉虫", translation: "Trilobite" },
  { source: "始祖鳥", translation: "Archaeopteryx" },
  { source: "シファクティヌス", translation: "Xiphactinus" },
  { source: "シャインホーン", translation: "Shinehorn" },
  { source: "シャスタサウルス", translation: "Shastasaurus" },
  { source: "ショートフェイスベア", translation: "Dire Bear" },
  { source: "シーラカンス", translation: "Coelacanth" },
  { source: "スカウト", translation: "Scout" },
  { source: "(特定条件で攻撃的)", translation: "Extinction" },
  { source: "ステゴサウルス", translation: "Stegosaurus" },
  { source: "スピノサウルス", translation: "Spino" },
  { source: "スプリング・ドレイクリング", translation: "Drakeling" },
  { source: "スロール", translation: "Thrall" },
  { source: "(特定条件で攻撃的)", translation: "Lost Colony" },
  { source: "セイバートゥース・サーモン", translation: "Sabertooth Salmon" },
  { source: "ソルウィン", translation: "Solwyn" },
  { source: "ダイアウルフ", translation: "Direwolf" },
  { source: "ダイアホッキョクグマ", translation: "Dire Polar Bear" },
  { source: "ダエオドン", translation: "Daeodon" },
  { source: "タペヤラ", translation: "Tapejara" },
  { source: "ダンクルオステウス", translation: "Dunkleosteus" },
  { source: "チョークエレメンタル", translation: "Chalk Elemental" },
  { source: "ティタノサウルス", translation: "Titanosaur" },
  { source: "ティタノボア", translation: "Titanoboa" },
  { source: "デイノスクス", translation: "Deinosuchus" },
  { source: "ディノテリウム", translation: "Deinotherium" },
  { source: "デイノニクス", translation: "Deinonychus" },
  { source: "ディプロカウルス", translation: "Diplocaulus" },
  { source: "ディプロドクス", translation: "Diplodocus" },
  { source: "ディメトロドン", translation: "Dimetrodon" },
  { source: "ディモルフォドン", translation: "Dimorphodon" },
  { source: "ティラコレオ", translation: "Thylacoleo" },
  { source: "ティラノサウルス", translation: "Rex" },
  { source: "ディロフォサウルス", translation: "Dilophosaur" },
  { source: "デスモダス", translation: "Desmodus" },
  { source: "テラーバード", translation: "Terror Bird" },
  { source: "テリジノサウルス", translation: "Therizinosaur" },
  { source: "デンキウナギ", translation: "Electrophorus" },
  { source: "トゥソテウティス", translation: "Tusoteuthis" },
  { source: "ドエディクルス", translation: "Doedicurus" },
  { source: "ドードー", translation: "Dodo" },
  { source: "トビネズミ", translation: "Jerboa" },
  { source: "トリケラトプス", translation: "Triceratops" },
  { source: "ドレッドノータス", translation: "Dreadnoughtus" },
  { source: "(特定条件で攻撃的)", translation: "Extinction" },
  { source: "ドレッドメア", translation: "" },
  { source: "ドレッドスタリオン", translation: "Dreadmare," },
  { source: "Dreadstallion", translation: "肉食" },
  { source: "トロオドン", translation: "Troodon" },
  { source: "猫", translation: "Cat" },
  { source: "友好的、", translation: "" },
  { source: "テリトリー型、", translation: "" },
  { source: "攻撃的", translation: "The Island" },
  { source: "バイソン", translation: "Bison" },
  { source: "パイロメイン", translation: "Pyromane" },
  { source: "パキケファロサウルス", translation: "Pachycephalosaurus" },
  { source: "パキリノサウルス", translation: "Pachyrhinosaurus" },
  { source: "ハゲワシ", translation: "Vulture" },
  { source: "(特定条件で攻撃的)", translation: "Scorched Earth" },
  { source: "バジリスク", translation: "Basilisk" },
  { source: "バシロサウルス", translation: "Basilosaurus" },
  { source: "パラケラテリウム", translation: "Paracer" },
  { source: "パラサウロロフス", translation: "Parasaur" },
  { source: "バリオニクス", translation: "Baryonyx" },
  { source: "バルブドッグ", translation: "Bulbdog" },
  { source: "ヒエノドン", translation: "Hyaenodon" },
  { source: "(特定状況で攻撃的)", translation: "The Island" },
  { source: "ヒツジ", translation: "Ovis" },
  { source: "ヒル", translation: "Leech" },
  { source: "ファイアワイバーン", translation: "Wyvern" },
  { source: "ファソラスクス", translation: "Fasolasuchus" },
  { source: "フィオミア", translation: "Phiomia" },
  { source: "フェザーライト", translation: "Featherlight" },
  { source: "フェニックス", translation: "Phoenix" },
  { source: "フェロクス", translation: "Ferox" },
  { source: "（特定条件で攻撃的）", translation: "Genesis Part 1" },
  { source: "プテラノドン", translation: "Pteranodon" },
  { source: "ブラッドストーカー", translation: "Bloodstalker" },
  { source: "プルモノスコルピウス", translation: "Pulmonoscorpius" },
  { source: "プルロヴィア", translation: "Purlovia" },
  { source: "プレシオサウルス", translation: "Plesiosaur" },
  { source: "プロコプトドン", translation: "Procoptodon" },
  { source: "ブローバック", translation: "Burrowbuck" },
  { source: "ブロントサウルス", translation: "Bronto" },
  { source: "フンコロガシ", translation: "Dung Beetle" },
  { source: "ペゴマスタクス", translation: "Pegomastax" },
  { source: "ヘスペロルニス", translation: "Hesperornis" },
  { source: "ペラゴルニス", translation: "Pelagornis" },
  { source: "ヘリコプリオン", translation: "Helicoprion" },
  { source: "ベールウィン", translation: "Veilwyn" },
  { source: "ベールゼブフォ", translation: "Beelzebufo" },
  { source: "ベロナサウルス", translation: "Velonasaur" },
  { source: "ポイズンワイバーン", translation: "Wyvern" },
  { source: "マグマサウルス", translation: "Magmasaur" },
  { source: "マナガルム", translation: "Managarmr" },
  { source: "マルウィン", translation: "Malwyn" },
  { source: "マンタ", translation: "Manta" },
  { source: "マンモス", translation: "Mammoth" },
  { source: "ミクロラプトル", translation: "Microraptor" },
  { source: "メイグアナ", translation: "Maeguana" },
  { source: "メガケロン", translation: "Megachelon" },
  { source: "メガテリウム", translation: "Megatherium" },
  { source: "(特定条件で攻撃的)", translation: "The Island" },
  { source: "メガピラニア", translation: "Piranha" },
  { source: "メガラニア", translation: "Megalania" },
  { source: "メガラプトル", translation: "Megaraptor" },
  { source: "メガロケロス", translation: "Megaloceros" },
  { source: "メガロサウルス", translation: "Megalosaurus" },
  { source: "メガロドン", translation: "Megalodon" },
  { source: "メソピテクス", translation: "Mesopithecus" },
  { source: "モササウルス", translation: "Mosasaurus" },
  { source: "モスコプス", translation: "Moschops" },
  { source: "モレラトプス", translation: "Morellatops" },
  { source: "(特定条件で受動的)", translation: "Scorched Earth" },
  { source: "モロクトカゲ", translation: "Thorny Dragon" },
  { source: "ヤツメウナギ", translation: "Lamprey" },
  { source: "ユウティラヌス", translation: "Yutyrannus" },
  { source: "雪フクロウ", translation: "Snow Owl" },
  { source: "ユタラプトル", translation: "Raptor" },
  { source: "ライトニングワイバーン", translation: "Wyvern" },
  { source: "ラベジャー", translation: "Ravager" },
  { source: "リオプレウロドン", translation: "Liopleurodon" },
  { source: "(特定条件で攻撃的)", translation: "The Island" },
  { source: "リストロサウルス", translation: "Lystrosaurus" },
  { source: "リニオグナタ", translation: "Rhyniognatha" },
  { source: "リーパーキング", translation: "Reaper King" },
  { source: "リマントリア", translation: "Lymantria" },
  { source: "ロックエレメンタル", translation: "Rock Elemental" },
  { source: "ロックドレイク", translation: "Rock Drake" },
  { source: "ロールラット", translation: "Roll Rat" },
  { source: "Iceworm Queen", translation: "アイスワーム(女王)" },
  { source: "Ice Wyvern", translation: "アイスワイバーン" },
  { source: "Astrocetus", translation: "アストロセタス" },
  { source: "Astrodelphis", translation: "アストロデルフィス" },
  { source: "Attack Drone", translation: "アタックドローン" },
  { source: "Achatina", translation: "アフリカマイマイ" },
  { source: "Aberrant Achatina", translation: "アフリカマイマイ変種" },
  { source: "Amargasaurus", translation: "アマルガサウルス" },
  { source: "Araneo", translation: "アラネオモーフス" },
  { source: "Spider", translation: "アラネオモーフス" },
  { source: "Aberrant Araneo", translation: "アラネオモーフス変種" },
  { source: "Argentavis", translation: "アルゲンタヴィス" },
  { source: "Alpha X-Triceratops", translation: "アルファ・Xトリケラトプス" },
  { source: "Alpha Karkinos", translation: "アルファ・カルキノス" },
  { source: "Alpha Carno", translation: "アルファ・カルノタウルス" },
  { source: "Alpha Carnotaurus", translation: "アルファ・カルノタウルス" },
  { source: "Alpha King Titan", translation: "アルファ・コロッサル・タイタン" },
  {
    source: "Alpha Surface Reaper King",
    translation: "アルファ・サーフェス・リーパーキング",
  },
  { source: "Alpha Deathworm", translation: "アルファ・デスワーム" },
  { source: "Alpha Tusoteuthis", translation: "アルファ・トゥソテウティス" },
  { source: "Alpha Basilisk", translation: "アルファ・バジリスク" },
  { source: "Alpha Fire Wyvern", translation: "アルファ・ファイアワイバーン" },
  {
    source: "Alpha Blood Crystal Wyvern",
    translation: "アルファ・ブラッド・クリスタルワイバーン",
  },
  { source: "Alpha Megalodon", translation: "アルファ・メガロドン" },
  { source: "Alpha Mosasaur", translation: "アルファ・モササウルス" },
  { source: "Alpha Mosasaurus", translation: "アルファ・モササウルス" },
  { source: "Alpha Raptor", translation: "アルファ・ラプトル" },
  { source: "Alpha Leedsichthys", translation: "アルファ・リードシクティス" },
  { source: "Alpha T-Rex", translation: "アルファ・レックス" },
  { source: "Allosaurus", translation: "アロサウルス" },
  { source: "Ankylo", translation: "アンキロサウルス" },
  { source: "Ankylosaurus", translation: "アンキロサウルス" },
  { source: "Aberrant Ankylosaurus", translation: "アンキロサウルス変種" },
  { source: "Angler", translation: "アンコウ" },
  { source: "Anglerfish", translation: "アンコウ" },
  { source: "Aberrant Anglerfish", translation: "アンコウ変種" },
  { source: "Andrewsarchus", translation: "アンドリューサルクス" },
  { source: "Ammonite", translation: "アンモナイト" },
  { source: "Yeti", translation: "イエティ" },
  { source: "Iguanodon", translation: "イグアノドン" },
  { source: "Aberrant Iguanodon", translation: "イグアノドン変種" },
  { source: "Ichthy", translation: "イクチオサウルス" },
  { source: "Ichthyosaurus", translation: "イクチオサウルス" },
  { source: "Ichthyornis", translation: "イクチオルニス" },
  { source: "Voidwyrm", translation: "ヴォイドワーム" },
  { source: "Eurypterid", translation: "ウミサソリ" },
  { source: "Equus", translation: "エクウス" },
  { source: "Aberrant Equus", translation: "エクウス変種" },
  { source: "Exo-Mek", translation: "エクソMEK" },
  {
    source: "Malfunctioned Mek Knight",
    translation: "エラーを起こしたMEKナイト",
  },
  {
    source: "Malfunctioned Tek Giganotosaurus",
    translation: "エラーを起こしたTEKギガノトサウルス",
  },
  {
    source: "Malfunctioned Tek Quetzal",
    translation: "エラーを起こしたTEKケツァルコアトルス",
  },
  {
    source: "Malfunctioned Tek Stegosaurus",
    translation: "エラーを起こしたTEKステゴサウルス",
  },
  {
    source: "Malfunctioned Tek Stryder",
    translation: "エラーを起こしたTEKストライダー",
  },
  {
    source: "Malfunctioned Tek Rex",
    translation: "エラーを起こしたTEKティラノサウルス",
  },
  {
    source: "Malfunctioned Tek Triceratops",
    translation: "エラーを起こしたTEKトリケラトプス",
  },
  {
    source: "Malfunctioned Tek Parasaur",
    translation: "エラーを起こしたTEKパラサウロロフス",
  },
  {
    source: "Malfunctioned Tek Raptor",
    translation: "エラーを起こしたTEKユタラプトル",
  },
  {
    source: "Malfunctioned Attack Drone",
    translation: "エラーを起こしたアタックドローン",
  },
  {
    source: "Malfunctioned Enforcer",
    translation: "エラーを起こしたエンフォーサー",
  },
  {
    source: "Brute Malfunctioned Tek Giganotosaurus",
    translation: "エラーを起こした凶暴なTEKギガノトサウルス",
  },
  {
    source: "Brute Malfunctioned Tek Rex",
    translation: "エラーを起こした凶暴なTEKティラノサウルス",
  },
  {
    source: "Malfunctioned Defense Unit",
    translation: "エラーを起こした防御ユニット",
  },
  {
    source: "Elemental Reaper King",
    translation: "エレメンタル・リーパーキング",
  },
  {
    source: "Ember Crystal Wyvern",
    translation: "エンバー・クリスタルワイバーン",
  },
  { source: "Enforcer", translation: "エンフォーサー" },
  { source: "Oviraptor", translation: "オヴィラプトル" },
  { source: "Onyc", translation: "オニコニクテリス" },
  { source: "Onychonycteris", translation: "オニコニクテリス" },
  { source: "Kairuku", translation: "カイルクペンギン" },
  { source: "Castoroides", translation: "カストロイデス" },
  { source: "Gasbag", translation: "ガスバッグ" },
  { source: "Gasbags", translation: "ガスバッグ" },
  { source: "Gacha", translation: "ガチャ" },
  { source: "GachaClaus", translation: "ガチャクロース" },
  { source: "Kaprosuchus", translation: "カプロスクス" },
  { source: "Mantis", translation: "カマキリ" },
  { source: "Chalicotherium", translation: "カリコテリウム" },
  { source: "Gallimimus", translation: "ガリミムス" },
  { source: "Carcharodontosaurus", translation: "カルカロドントサウルス" },
  {
    source: "ファイル:Carcharodonto.png Carcharodonto",
    translation: "カルカロドントサウルス",
  },
  { source: "Karkinos", translation: "カルキノス" },
  { source: "Carno", translation: "カルノタウルス" },
  { source: "Carnotaurus", translation: "カルノタウルス" },
  { source: "Aberrant Carnotaurus", translation: "カルノタウルス変種" },
  { source: "Carbonemys", translation: "カルボネミス" },
  { source: "Aberrant Carbonemys", translation: "カルボネミス変種" },
  { source: "Otter", translation: "カワウソ" },
  { source: "Aberrant Otter", translation: "カワウソ変種" },
  { source: "Gamma King Titan", translation: "ガンマ・コロッサル・タイタン" },
  { source: "Giganotosaurus", translation: "ギガノトサウルス" },
  { source: "Gigantopithecus", translation: "ギガントピテクス" },
  { source: "Aberrant Gigantopithecus", translation: "ギガントピテクス変種" },
  { source: "Cnidaria", translation: "クニダリア" },
  { source: "Aberrant Cnidaria", translation: "クニダリア変種" },
  { source: "Crystal Wyvern", translation: "クリスタルワイバーン" },
  {
    source: "Crystal Wyvern Queen",
    translation: "クリスタルワイバーンクイーン",
  },
  {
    source: "Crystal Wyvern Queen (Alpha)",
    translation: "クリスタルワイバーンクイーン(アルファ)",
  },
  {
    source: "Crystal Wyvern Queen (Gamma)",
    translation: "クリスタルワイバーンクイーン(ガンマ)",
  },
  {
    source: "Crystal Wyvern Queen (Beta)",
    translation: "クリスタルワイバーンクイーン(ベータ)",
  },
  { source: "Griffin", translation: "グリフィン" },
  { source: "Glowtail", translation: "グローテール" },
  { source: "Glowbug", translation: "グローバグ" },
  { source: "Quetzal", translation: "ケツァルコアトルス" },
  { source: "Quetzalcoatlus", translation: "ケツァルコアトルス" },
  { source: "Woolly Rhino", translation: "ケブカサイ" },
  { source: "Woolly Rhinoceros", translation: "ケブカサイ" },
  { source: "Kentrosaurus", translation: "ケントロサウルス" },
  { source: "Mantis Ghost", translation: "ゴーストカマキリ" },
  {
    source: "Surface Reaper King Ghost",
    translation: "ゴーストサーフェス・リーパーキング",
  },
  { source: "Direwolf Ghost", translation: "ゴーストダイアウルフ" },
  { source: "Rex Ghost", translation: "ゴーストティラノサウルス" },
  { source: "Basilisk Ghost", translation: "ゴーストバジリスク" },
  { source: "Bulbdog Ghost", translation: "ゴーストバルブドッグ" },
  { source: "Snow Owl Ghost", translation: "ゴースト雪フクロウ" },
  { source: "King Titan", translation: "コロッサル・タイタン" },
  { source: "Compsognathus", translation: "コンプソグナトゥス" },
  { source: "Compy", translation: "コンプソグナトゥス" },
  { source: "Surface Reaper King", translation: "サーフェス・リーパーキング" },
  { source: "Sabertooth", translation: "サーベルタイガー" },
  { source: "Smilodon", translation: "サーベルタイガー" },
  { source: "Aberrant Salmon", translation: "サーモン変種" },
  {
    source: "Subterranean Reaper King",
    translation: "サブテラニアン・リーパーキング",
  },
  { source: "Summoner", translation: "サモナー" },
  { source: "Sarco", translation: "サルコスクス" },
  { source: "Sarcosuchus", translation: "サルコスクス" },
  { source: "Aberrant Sarco", translation: "サルコスクス変種" },
  { source: "Seeker", translation: "シーカー" },
  { source: "Coelacanth", translation: "シーラカンス" },
  { source: "Abberant Coelacanth", translation: "シーラカンス変種" },
  { source: "Aberrant Coelacanth", translation: "シーラカンス変種" },
  { source: "Sinomacrops", translation: "シノマクロプス" },
  { source: "Shinehorn", translation: "シャインホーン" },
  { source: "Jug Bug", translation: "ジャグ・バグ" },
  { source: "Oil Jug Bug", translation: "ジャグ・バグ(原油)" },
  { source: "Shadowmane", translation: "シャドウメイン" },
  { source: "Dire Bear", translation: "ショートフェイスベア" },
  { source: "Aberrant Dire Bear", translation: "ショートフェイスベア変種" },
  { source: "Super Turkey", translation: "スーパー七面鳥" },
  { source: "Scout", translation: "スカウト" },
  { source: "Skeletal Carnotaurus", translation: "スケルタル・カルノタウルス" },
  {
    source: "Skeletal Giganotosaurus",
    translation: "スケルタル・ギガノトサウルス",
  },
  { source: "Skeletal Quetzal", translation: "スケルタル・ケツァルコアトルス" },
  { source: "Skeletal Stego", translation: "スケルタル・ステゴサウルス" },
  { source: "Skeletal Rex", translation: "スケルタル・ティラノサウルス" },
  { source: "Skeletal Jerboa", translation: "スケルタル・トビネズミ" },
  { source: "Skeletal Trike", translation: "スケルタル・トリケラトプス" },
  { source: "Skeletal Bronto", translation: "スケルタル・ブロントサウルス" },
  { source: "Skeletal Raptor", translation: "スケルタル・ユタラプトル" },
  { source: "Sköll", translation: "スコル" },
  { source: "Steinbjörn", translation: "スタインヨルン" },
  { source: "Stygimoloch", translation: "スティギモロク" },
  { source: "Styracosaurus", translation: "スティラコサウルス" },
  { source: "Stegosaurus", translation: "ステゴサウルス" },
  { source: "Aberrant Stegosaurus", translation: "ステゴサウルス変種" },
  { source: "Spino", translation: "スピノサウルス" },
  { source: "Aberrant Spino", translation: "スピノサウルス変種" },
  {
    source: "Spirit Dire Bear",
    translation: "スピリット・ショートフェイスベア",
  },
  {
    source: "Spirit Direbear",
    translation: "スピリット・ショートフェイスベア",
  },
  { source: "Spirit Direwolf", translation: "スピリット・ダイアウルフ" },
  { source: "Sabertooth Salmon", translation: "セイバートゥース・サーモン" },
  {
    source: "Aberrant Sabertooth Salmon",
    translation: "セイバートゥース・サーモン変種",
  },
  { source: "Zomdodo", translation: "ゾンビドードー" },
  { source: "Zombie Fire Wyvern", translation: "ゾンビファイアワイバーン" },
  { source: "Zombie Poison Wyvern", translation: "ゾンビポイズンワイバーン" },
  {
    source: "Zombie Lightning Wyvern",
    translation: "ゾンビライトニングワイバーン",
  },
  { source: "Zombie Wyvern", translation: "ゾンビワイバーン" },
  { source: "Direwolf", translation: "ダイアウルフ" },
  { source: "Dire Polar Bear", translation: "ダイアホッキョクグマ" },
  { source: "Titans", translation: "タイタン" },
  { source: "Daeodon", translation: "ダエオドン" },
  { source: "Tapejara", translation: "タペヤラ" },
  { source: "Dunkleosteus", translation: "ダンクルオステウス" },
  { source: "ファイル:Dunkle.png Dunkle", translation: "ダンクルオステウス" },
  { source: "Chalk Golem", translation: "チョークエレメンタル" },
  { source: "Titanosaur", translation: "ティタノサウルス" },
  { source: "Titanoboa", translation: "ティタノボア" },
  { source: "Aberrant Titanoboa", translation: "ティタノボア変種" },
  { source: "Titanomyrma", translation: "ティタノミルマ" },
  { source: "Titanomyrma Soldier", translation: "ティタノミルマ・ソルジャー" },
  { source: "Titanomyrma Drone", translation: "ティタノミルマ・ドローン" },
  { source: "Deinonychus", translation: "デイノニクス" },
  { source: "Dinopithecus", translation: "ディノピテクス" },
  { source: "Dinopithecus King", translation: "ディノピテクスキング" },
  {
    source: "Dinopithecus King (Alpha)",
    translation: "ディノピテクスキング(アルファ)",
  },
  {
    source: "Dinopithecus King (Gamma)",
    translation: "ディノピテクスキング(ガンマ)",
  },
  {
    source: "Dinopithecus King (Beta)",
    translation: "ディノピテクスキング(ベータ)",
  },
  { source: "Diplocaulus", translation: "ディプロカウルス" },
  { source: "Aberrant Diplocaulus", translation: "ディプロカウルス変種" },
  { source: "Diplodocus", translation: "ディプロドクス" },
  { source: "Aberrant Diplodocus", translation: "ディプロドクス変種" },
  { source: "Dimetrodon", translation: "ディメトロドン" },
  { source: "Aberrant Dimetrodon", translation: "ディメトロドン変種" },
  { source: "Dimorphodon", translation: "ディモルフォドン" },
  { source: "Aberrant Dimorphodon", translation: "ディモルフォドン変種" },
  { source: "Thylacoleo", translation: "ティラコレオ" },
  { source: "Rex", translation: "ティラノサウルス" },
  { source: "Tyrannosaurus Rex", translation: "ティラノサウルス" },
  { source: "Dilo", translation: "ディロフォサウルス" },
  { source: "Dilophosaur", translation: "ディロフォサウルス" },
  { source: "Desert Titan", translation: "デザート・タイタン" },
  { source: "Desert Titan Flock", translation: "デザート・タイタンの群れ" },
  { source: "Desmodus", translation: "デスモダス" },
  { source: "Deathworm", translation: "デスワーム" },
  {
    source: "ファイル:Deathworm (Minion).png Deathworm (Minion)",
    translation: "デスワーム (ミニオン)",
  },
  { source: "Terror Bird", translation: "テラーバード" },
  { source: "Therizinosaur", translation: "テリジノサウルス" },
  { source: "Therizinosaurus", translation: "テリジノサウルス" },
  { source: "Electrophorus", translation: "デンキウナギ" },
  { source: "Aberrant Electrophorus", translation: "デンキウナギ変種" },
  { source: "Tusoteuthis", translation: "トゥソテウティス" },
  { source: "Doedicurus", translation: "ドエディクルス" },
  { source: "Aberrant Doedicurus", translation: "ドエディクルス変種" },
  { source: "Dodo", translation: "ドードー" },
  { source: "DodoRex", translation: "ドードーレックス" },
  { source: "Dodo Wyvern", translation: "ドードーワイバーン" },
  { source: "Aberrant Dodo", translation: "ドードー変種" },
  { source: "Jerboa", translation: "トビネズミ" },
  { source: "Dragon", translation: "ドラゴン" },
  { source: "Dragon (Alpha)", translation: "ドラゴン(アルファ)" },
  { source: "Dragon (Gamma)", translation: "ドラゴン(ガンマ)" },
  { source: "Dragon (Beta)", translation: "ドラゴン(ベータ)" },
  { source: "Triceratops", translation: "トリケラトプス" },
  { source: "Trike", translation: "トリケラトプス" },
  { source: "Aberrant Triceratops", translation: "トリケラトプス変種" },
  { source: "Troodon", translation: "トロオドン" },
  {
    source: "Tropical Crystal Wyvern",
    translation: "トロピカル・クリスタルワイバーン",
  },
  { source: "Tropeognathus", translation: "トロペオグナトゥス" },
  { source: "Nameless", translation: "ネームレス" },
  { source: "Noglin", translation: "ノグリン" },
  { source: "Party Dodo", translation: "パーティードードー" },
  { source: "Pachy", translation: "パキケファロサウルス" },
  { source: "Pachycephalosaurus", translation: "パキケファロサウルス" },
  { source: "Pachyrhino", translation: "パキリノサウルス" },
  { source: "Pachyrhinosaurus", translation: "パキリノサウルス" },
  { source: "Vulture", translation: "ハゲワシ" },
  { source: "Basilisk", translation: "バジリスク" },
  { source: "Basilosaurus", translation: "バシロサウルス" },
  { source: "Hati", translation: "ハティ" },
  { source: "Hati and Sköll", translation: "ハティとスコル" },
  { source: "Bunny Oviraptor", translation: "バニーオヴィラプトル" },
  { source: "Bunny Dodo", translation: "バニードードー" },
  { source: "Parakeet Fish School", translation: "パラキートの魚群" },
  { source: "Paracer", translation: "パラケラテリウム" },
  { source: "Paraceratherium", translation: "パラケラテリウム" },
  { source: "Aberrant Paraceratherium", translation: "パラケラテリウム変種" },
  { source: "Parasaur", translation: "パラサウロロフス" },
  { source: "Parasaurolophus", translation: "パラサウロロフス" },
  { source: "Aberrant Parasaur", translation: "パラサウロロフス変種" },
  { source: "Baryonyx", translation: "バリオニクス" },
  { source: "Aberrant Baryonyx", translation: "バリオニクス変種" },
  { source: "Bulbdog", translation: "バルブドッグ" },
  { source: "Hyaenodon", translation: "ヒエノドン" },
  { source: "Ovis", translation: "ヒツジ" },
  { source: "Aberrant Ovis", translation: "ヒツジ変種" },
  { source: "Leech", translation: "ヒル" },
  { source: "Fire Wyvern", translation: "ファイアワイバーン" },
  {
    source: "ファイル:Broodmother Guardian.png Broodmother Guardian",
    translation: "ファイル:Broodmother Guardian.png Broodmother Guardian",
  },
  {
    source: "ファイル:Megapithecus Guardian.png Megapithecus Guardian",
    translation: "ファイル:Megapithecus Guardian.png Megapithecus Guardian",
  },
  {
    source: "ファイル:Eerie Leech (Diseased).png Eerie Leech (Diseased)",
    translation:
      "ファイル:Mobile Eerie Leech (Diseased).png Eerie Leech (Diseased) (ARK: Survival Evolved Mobile)",
  },
  {
    source: "ファイル:Iceworm Queen Arena.png Iceworm Queen Arena",
    translation:
      "ファイル:アイスワーム(女王) (アリーナ).png アイスワーム(女王) (アリーナ)",
  },
  {
    source: "ファイル:Surface Seeker.png Surface Seeker",
    translation: "ファイル:サーフェス・シーカー.png サーフェス・シーカー",
  },
  {
    source: "Water Jug Bug",
    translation: "ファイル:ジャグバグ(水).png ジャグバグ(水)",
  },
  {
    source: "Bone Fire Wyvern",
    translation:
      "ファイル:スケルタル・ファイアワイバーン.png スケルタル・ファイアワイバーン",
  },
  { source: "Phiomia", translation: "フィオミア" },
  { source: "Fjordhawk", translation: "フィヨルドホーク" },
  { source: "Featherlight", translation: "フェザーライト" },
  { source: "Phoenix", translation: "フェニックス" },
  { source: "Ferox", translation: "フェロクス" },
  { source: "Ferox (Large)", translation: "フェロクス (大)" },
  { source: "Fenrir", translation: "フェンリル" },
  { source: "Fenrisúlfr", translation: "フェンリル (ボス)" },
  { source: "Fenrisúlfr (Alpha)", translation: "フェンリル(アルファ)" },
  { source: "Fenrisúlfr (Gamma)", translation: "フェンリル(ガンマ)" },
  { source: "Fenrisúlfr (Beta)", translation: "フェンリル(ベータ)" },
  { source: "Forest Titan", translation: "フォレスト・タイタン" },
  { source: "Forest Wyvern", translation: "フォレストワイバーン" },
  { source: "Pteranodon", translation: "プテラノドン" },
  {
    source: "Blood Crystal Wyvern",
    translation: "ブラッド・クリスタルワイバーン",
  },
  { source: "Bloodstalker", translation: "ブラッドストーカー" },
  { source: "Broodmother", translation: "ブルードマザー" },
  { source: "Broodmother Lysrix", translation: "ブルードマザー" },
  {
    source: "Broodmother Lysrix (Alpha)",
    translation: "ブルードマザー(アルファ)",
  },
  {
    source: "Broodmother Lysrix (Gamma)",
    translation: "ブルードマザー(ガンマ)",
  },
  {
    source: "Broodmother Lysrix (Beta)",
    translation: "ブルードマザー(ベータ)",
  },
  { source: "Pulmonoscorpius", translation: "プルモノスコルピウス" },
  { source: "Scorpion", translation: "プルモノスコルピウス" },
  {
    source: "Aberrant Pulmonoscorpius",
    translation: "プルモノスコルピウス変種",
  },
  { source: "Purlovia", translation: "プルロヴィア" },
  { source: "Polar Purlovia", translation: "プルロヴィア (雪原)" },
  { source: "Aberrant Purlovia", translation: "プルロヴィア変種" },
  { source: "Plesiosaur", translation: "プレシオサウルス" },
  { source: "Procoptodon", translation: "プロコプトドン" },
  { source: "Bronto", translation: "ブロントサウルス" },
  { source: "Brontosaurus", translation: "ブロントサウルス" },
  { source: "Dung Beetle", translation: "フンコロガシ" },
  { source: "Aberrant Dung Beetle", translation: "フンコロガシ変種" },
  { source: "Beyla", translation: "ベイラ" },
  { source: "Beyla Spawn", translation: "ベイラ・スポーン" },
  { source: "Beta King Titan", translation: "ベータ・コロッサル・タイタン" },
  { source: "Beelzebufo", translation: "ベールゼブフォ" },
  { source: "Aberrant Beelzebufo", translation: "ベールゼブフォ変種" },
  { source: "Pegomastax", translation: "ペゴマスタクス" },
  { source: "Hesperornis", translation: "ヘスペロルニス" },
  { source: "Pelagornis", translation: "ペラゴルニス" },
  { source: "Velonasaur", translation: "ベロナサウルス" },
  { source: "Poison Wyvern", translation: "ポイズンワイバーン" },
  { source: "Bosses", translation: "ボス" },
  { source: "Polar Bear", translation: "ホッキョクグマ" },
  { source: "Magmasaur", translation: "マグマサウルス" },
  { source: "Macro-Summoner", translation: "マクロ・サモナー" },
  { source: "Macrophage", translation: "マクロファージ" },
  { source: "Managarmr", translation: "マナガルム" },
  { source: "Manta", translation: "マンタ" },
  { source: "Aberrant Manta", translation: "マンタ変種" },
  { source: "Manticore", translation: "マンティコア" },
  { source: "Manticore (Alpha)", translation: "マンティコア(アルファ)" },
  { source: "Manticore (Gamma)", translation: "マンティコア(ガンマ)" },
  { source: "Manticore (Beta)", translation: "マンティコア(ベータ)" },
  { source: "Mammoth", translation: "マンモス" },
  { source: "Microraptor", translation: "ミクロラプトル" },
  { source: "Maewing", translation: "メイウィング" },
  { source: "Mega Mek", translation: "メガMEK" },
  { source: "Megachelon", translation: "メガケロン" },
  { source: "Megatherium", translation: "メガテリウム" },
  { source: "Meganeura", translation: "メガネウラ" },
  { source: "Aberrant Meganeura", translation: "メガネウラ変種" },
  { source: "Megapithecus", translation: "メガピテクス" },
  { source: "Megapithecus (Alpha)", translation: "メガピテクス(アルファ)" },
  { source: "Megapithecus (Gamma)", translation: "メガピテクス(ガンマ)" },
  { source: "Megapithecus (Beta)", translation: "メガピテクス(ベータ)" },
  { source: "Megapiranha", translation: "メガピラニア" },
  { source: "Piranha", translation: "メガピラニア" },
  { source: "Aberrant Piranha", translation: "メガピラニア変種" },
  { source: "Megalania", translation: "メガラニア" },
  { source: "Aberrant Megalania", translation: "メガラニア変種" },
  { source: "Megaloceros", translation: "メガロケロス" },
  { source: "Megalosaurus", translation: "メガロサウルス" },
  { source: "Aberrant Megalosaurus", translation: "メガロサウルス変種" },
  { source: "Megalodon", translation: "メガロドン" },
  { source: "Mesopithecus", translation: "メソピテクス" },
  { source: "Mosasaurus", translation: "モササウルス" },
  { source: "Moschops", translation: "モスコプス" },
  { source: "Aberrant Moschops", translation: "モスコプス変種" },
  { source: "Morellatops", translation: "モレラトプス" },
  {
    source: "ファイル:Camelsaurus.png Camelsaurus",
    translation: "モレラトプス",
  },
  { source: "Thorny Dragon", translation: "モロクトカゲ" },
  { source: "Lamprey", translation: "ヤツメウナギ" },
  { source: "Yutyrannus", translation: "ユウティラヌス" },
  { source: "Raptor", translation: "ユタラプトル" },
  { source: "Utahraptor", translation: "ユタラプトル" },
  { source: "Aberrant Raptor", translation: "ユタラプトル変種" },
  { source: "Unicorn", translation: "ユニコーン" },
  { source: "Lightning Wyvern", translation: "ライトニングワイバーン" },
  { source: "Lava Elemental", translation: "ラヴァエレメンタル" },
  { source: "Raptor Claus", translation: "ラプトルクロース" },
  { source: "Rubble Bear", translation: "ラブル・ベアー" },
  { source: "Rubble Golem", translation: "ラブルゴーレム" },
  { source: "Ravager", translation: "ラベジャー" },
  { source: "Leedsichthys", translation: "リードシクティス" },
  { source: "Reaper", translation: "リーパー" },
  { source: "Reaper King", translation: "リーパーキング" },
  { source: "Reaper Queen", translation: "リーパークイーン" },
  { source: "Reaper Prince", translation: "リーパープリンス" },
  { source: "Liopleurodon", translation: "リオプレウロドン" },
  { source: "Lystrosaurus", translation: "リストロサウルス" },
  { source: "Aberrant Lystrosaurus", translation: "リストロサウルス変種" },
  { source: "Lymantria", translation: "リマントリア" },
  {
    source: "Rare X-Sabertooth Salmon",
    translation: "レアXセイバートゥース・サーモン",
  },
  { source: "Roll Rat", translation: "ロールラット" },
  { source: "Rockwell", translation: "ロックウェル" },
  { source: "Rockwell Node", translation: "ロックウェル・ノード" },
  { source: "Rockwell Prime", translation: "ロックウェル・プライム" },
  {
    source: "Rockwell Prime (Alpha)",
    translation: "ロックウェル・プライム(アルファ)",
  },
  {
    source: "Rockwell Prime (Gamma)",
    translation: "ロックウェル・プライム(ガンマ)",
  },
  {
    source: "Rockwell Prime (Beta)",
    translation: "ロックウェル・プライム(ベータ)",
  },
  {
    source: "ファイル:Rockwell Prime Tentacle.png Rockwell Prime Tentacle",
    translation: "ロックウェル・プライムの触手",
  },
  { source: "Rockwell (Alpha)", translation: "ロックウェル(アルファ)" },
  { source: "Rockwell (Gamma)", translation: "ロックウェル(ガンマ)" },
  { source: "Rockwell (Beta)", translation: "ロックウェル(ベータ)" },
  { source: "Rockwell Tentacle", translation: "ロックウェルの触手" },
  {
    source: "RockwellTentacle (Alpha)",
    translation: "ロックウェルの触手(アルファ)",
  },
  {
    source: "RockwellTentacle (Gamma)",
    translation: "ロックウェルの触手(ガンマ)",
  },
  {
    source: "RockwellTentacle (Beta)",
    translation: "ロックウェルの触手(ベータ)",
  },
  { source: "Rock Elemental", translation: "ロックエレメンタル" },
  { source: "Rock Drake", translation: "ロックドレイク" },
  { source: "Wyvern", translation: "ワイバーン" },
  {
    source: "Corrupted Arthropluera",
    translation: "汚染されたアースロプレウラ",
  },
  { source: "Corrupted Avatar", translation: "汚染されたアバター" },
  {
    source: "Corrupted Chalicotherium",
    translation: "汚染されたカリコテリウム",
  },
  { source: "Corrupted Carnotaurus", translation: "汚染されたカルノタウルス" },
  {
    source: "Corrupted Giganotosaurus",
    translation: "汚染されたギガノトサウルス",
  },
  { source: "Corrupted Survivor", translation: "汚染されたサバイバー" },
  { source: "Corrupted Stegosaurus", translation: "汚染されたステゴサウルス" },
  { source: "Corrupted Spino", translation: "汚染されたスピノサウルス" },
  {
    source: "Corrupted Dimorphodon",
    translation: "汚染されたディモルフォドン",
  },
  { source: "Corrupted Rex", translation: "汚染されたティラノサウルス" },
  {
    source: "Corrupted Dilophosaur",
    translation: "汚染されたディロフォサウルス",
  },
  { source: "Corrupted Deathworm", translation: "汚染されたデスワーム" },
  { source: "Corrupted Triceratops", translation: "汚染されたトリケラトプス" },
  {
    source: "Corrupted Paraceratherium",
    translation: "汚染されたパラケラテリウム",
  },
  { source: "Corrupted Pteranodon", translation: "汚染されたプテラノドン" },
  { source: "Corrupted Raptor", translation: "汚染されたユタラプトル" },
  { source: "Corrupted Reaper King", translation: "汚染されたリーパーキング" },
  { source: "Corrupted Rock Drake", translation: "汚染されたロックドレイク" },
  { source: "Corrupted Wyvern", translation: "汚染されたワイバーン" },
  { source: "Corrupted Master Controller", translation: "汚染された支配者" },
  {
    source: "Alpha Corrupted Master Controller",
    translation: "汚染された支配者(アルファ)",
  },
  {
    source: "Gamma Corrupted Master Controller",
    translation: "汚染された支配者(ガンマ)",
  },
  {
    source: "Beta Corrupted Master Controller",
    translation: "汚染された支配者(ベータ)",
  },
  { source: "Corrupt Tumor", translation: "汚染された腫瘍" },
  { source: "Corrupted Creatures", translation: "汚染された生物" },
  { source: "Overseer", translation: "監督者" },
  { source: "Overseer (Alpha)", translation: "監督者(アルファ)" },
  { source: "Overseer (Gamma)", translation: "監督者(ガンマ)" },
  { source: "Overseer (Beta)", translation: "監督者(ベータ)" },
  { source: "Giant Bee", translation: "巨大ハチ" },
  { source: "Giant Queen Bee", translation: "巨大女王バチ" },
  { source: "Brute X-Allosaurus", translation: "凶暴なXアロサウルス" },
  { source: "Brute X-Spino", translation: "凶暴なXスピノサウルス" },
  { source: "Brute X-Rex", translation: "凶暴なXティラノサウルス" },
  { source: "Brute X-Megalodon", translation: "凶暴なXメガロドン" },
  { source: "Brute X-Mosasaurus", translation: "凶暴なXモササウルス" },
  { source: "Brute X-Yutyrannus", translation: "凶暴なXユウティラヌス" },
  { source: "Brute X-Raptor", translation: "凶暴なXユタラプトル" },
  {
    source: "Brute X-Rock Elemental",
    translation: "凶暴なXロックエレメンタル",
  },
  { source: "Brute Astrocetus", translation: "凶暴なアストロセタス" },
  { source: "Brute Araneo", translation: "凶暴なアラネオモーフス" },
  { source: "Brute Araneo", translation: "凶暴なアラネオモーフス" },
  { source: "Brute Sarco", translation: "凶暴なサルコスクス" },
  { source: "Brute Seeker", translation: "凶暴なシーカー" },
  { source: "Brute Tusoteuthis", translation: "凶暴なトゥソテウティス" },
  { source: "Brute Basilosaurus", translation: "凶暴なバシロサウルス" },
  { source: "Brute Fire Wyvern", translation: "凶暴なファイアワイバーン" },
  { source: "Brute Ferox", translation: "凶暴なフェロクス" },
  { source: "Brute Bloodstalker", translation: "凶暴なブラッドストーカー" },
  { source: "Brute Plesiosaur", translation: "凶暴なプレシオサウルス" },
  { source: "Brute Magmasaur", translation: "凶暴なマグマサウルス" },
  { source: "Brute Mammoth", translation: "凶暴なマンモス" },
  { source: "Brute Megaloceros", translation: "凶暴なメガロケロス" },
  { source: "Brute Leedsichthys", translation: "凶暴なリードシクティス" },
  { source: "Brute Reaper King", translation: "凶暴なリーパーキング" },
  { source: "Golden Striped Megalodon", translation: "金縞のメガロドン" },
  {
    source: "Golden Striped Brute Megalodon",
    translation: "金縞の凶暴なメガロドン",
  },
  { source: "Enraged Triceratops", translation: "激怒したトリケラトプス" },
  {
    source: "Enraged Corrupted Rex",
    translation: "激怒した汚染されたティラノサウルス",
  },
  { source: "Enraged Creatures", translation: "激怒した生物" },
  { source: "Trilobite", translation: "三葉虫" },
  { source: "Aberrant Trilobite", translation: "三葉虫変種" },
  { source: "Archaeopteryx", translation: "始祖鳥" },
  { source: "Eel Minion", translation: "子ウナギ (ミニオン)" },
  { source: "Turkey", translation: "七面鳥" },
  {
    source: "Experimental Giganotosaurus",
    translation: "実験体ギガノトサウルス",
  },
  {
    source: "Moeder, Master of the Ocean",
    translation: "深海の女王・ムーダー",
  },
  {
    source: "Alpha Moeder, Master of the Ocean",
    translation: "深海の女王・ムーダー(アルファ)",
  },
  {
    source: "Gamma Moeder, Master of the Ocean",
    translation: "深海の女王・ムーダー(ガンマ)",
  },
  {
    source: "Beta Moeder, Master of the Ocean",
    translation: "深海の女王・ムーダー(ベータ)",
  },
  { source: "Human", translation: "人間" },
  { source: "Human (Female)", translation: "人間 (女)" },
  { source: "Human (Male)", translation: "人間 (男)" },
  { source: "Snow Owl", translation: "雪フクロウ" },
  { source: "Insect Swarm", translation: "虫の大群" },
  { source: "Diseased Leech", translation: "病気持ちのヒル" },
  {
    source: "Injured Brute Reaper King",
    translation: "負傷した凶暴なリーパーキング",
  },
  { source: "Defense Unit", translation: "防御ユニット" },
];

main();
