services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    tty: true
    volumes:
      - ..:/home/vscode/app
    networks:
      - shared-ai-net

networks:
  shared-ai-net:
    name: asb-web_ai-network
    external: true
