services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    tty: true
    volumes:
      - ..:/home/vscode/app
#   ollama:
#     image: ollama/ollama:latest
#     # build:
#     #   context: .
#     #   dockerfile: ollama.Dockerfile
#     ports:
#       - "11434:11434"
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: all          # すべてのGPUを指定
#               capabilities: [gpu] # 必須設定
#     volumes:
#       - ollama_data:/root/.ollama

# volumes:
#   ollama_data:
