name: cicd

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.14

      - name: checkout code
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: install package dependencies
        run: bun install --frozen-lockfile

      - name: check (biome)
        run: bun run biome

      - name: test
        run: bun run test

      - name: build web
        run: bun run build:apps:web

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build discord bot image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: discord-bot.Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload static files as artifact
        if: github.event_name == 'push'
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/dist/

  deploy-pages:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  push-discord-bot-image:
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    # if: github.event_name == 'push'
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: asb-ts_discord-bot
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: push discord bot image
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=gha
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.date.outputs.CURRENT_DATE }}
